require "prototypes/entities/cryoliquefier"
require "prototypes/entities/cryogrenade"
require "prototypes/fluids/boric-acid"
require "prototypes/fluids/deuterium-oxide"
require "prototypes/fluids/hydrogen-sulfide"